### ISSUE TITLE
Getting error "Error: ENODEV, No such device"

### ISSUE THREAD

**Issue by gijsprins93** [mKeRix/hassio-repo#11]
So the add-on does start, but only with the error message stated below. The configuration hasn't changed, I only upgraded HA from a RPi3b+ to a NUC.

```
/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:106
        throw e;
        ^
Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:101:37)
    at NobleBindings.init (/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:103:13)
    at /usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
[cmd] /room-assistant/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Complete log: 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:53:24] INFO: Setting up Home Assistant configuration
[08:53:24] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
1/14/2021, 8:53:28 AM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy, bluetooth-classic
1/14/2021, 8:53:29 AM - info - NestFactory: Starting Nest application...
1/14/2021, 8:53:29 AM - info - InstanceLoader: AppModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: ConfigModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: HttpModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: ClusterModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: TerminusModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: BluetoothModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: ScheduleModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: EntitiesModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
1/14/2021, 8:53:29 AM - info - InstanceLoader: StatusModule dependencies initialized
1/14/2021, 8:53:30 AM - info - RoutesResolver: EntitiesController {/entities}:
1/14/2021, 8:53:30 AM - info - RouterExplorer: Mapped {/entities, GET} route
1/14/2021, 8:53:30 AM - info - RoutesResolver: StatusController {/status}:
1/14/2021, 8:53:30 AM - info - RouterExplorer: Mapped {/status, GET} route
1/14/2021, 8:53:30 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://localhost:1883
1/14/2021, 8:53:30 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
1/14/2021, 8:53:30 AM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
1/14/2021, 8:53:30 AM - info - NestApplication: Nest application successfully started
/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:106
        throw e;
        ^
Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:101:37)
    at NobleBindings.init (/usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:103:13)
    at /usr/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
[cmd] /room-assistant/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by mKeRix** [comment]
I think the SSH add-on available from the official add-on store also includes some Bluetooth tooling, could you try going into that and executing `hciconfig`? It would be really helpful if you could paste the output of that here.

This error indicates that it couldn't find the Bluetooth adapter with the specified id. This could be because your adapter registers under a different ID for some reason, or because Home Assistant OS doesn't mount it correctly on the NUC.
