### ISSUE TITLE
Hassio addon won't start up

### ISSUE THREAD

**Issue by dave-sausages** [mKeRix/hassio-repo#3]
Hi,

I installed the addon okay. but when I go to start it, I get this error message in the log. Any ideas on how to get it running?

`make: Leaving directory '/room-assistant/node_modules/ffi/build'
> d6t@0.0.5 postinstall /room-assistant/node_modules/d6t
> make -C library/src/ && sudo make -C library/src install
make: Entering directory '/room-assistant/node_modules/d6t/library/src'
gcc -c d6t.c -I../include -W -Wall -O2 -fpic
gcc -c i2c-reg.c -I../include -W -Wall -O2 -fpic
i2c-reg.c:44:27: fatal error: linux/i2c-dev.h: No such file or directory
 #include <linux/i2c-dev.h>
                           ^
compilation terminated.
make: *** [Makefile:23: i2c-reg.o] Error 1
make: Leaving directory '/room-assistant/node_modules/d6t/library/src'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.2 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
{ Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  cause: 
   { Error: d6t@0.0.5 postinstall: `make -C library/src/ && sudo make -C library/src install`
Exit status 2
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     errno: 2,
     code: 'ELIFECYCLE',
     pkgid: 'd6t@0.0.5',
     stage: 'postinstall',
     script: 'make -C library/src/ && sudo make -C library/src install',
     pkgname: 'd6t' },
  errno: 2,
  code: 'ELIFECYCLE',
  pkgid: 'd6t@0.0.5',
  stage: 'postinstall',
  script: 'make -C library/src/ && sudo make -C library/src install',
  pkgname: 'd6t',
  parent: 'room-assistant' }`

**Comment by mKeRix** [comment]
It looks like you have the d6t component enabled in the `services` options (or maybe it is empty). Did you mean to do that? Because d6t isn't supported on Hass.io yet, as mentioned in the docs.

If you were looking to use other components - could you try to just add those to the `services` and then run the add-on again?

**Comment by mKeRix** [comment]
Should not be an issue anymore with v2.0 :)
